# Generated by Django 2.2.3 on 2019-09-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=150, verbose_name='Title')),
            ],
            options={
                'db_table': 'tb_skill',
            },
        ),
    ]
